spring:
  application:
    name: order

  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:${spring.sql.init.platform}://101.35.251.170:3306/kira_cloud?createDatabaseIfNotExist=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Zhangxu00!
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Spring Boot 2.6后，默认不建议循环引用。 需手动设置
  main:
    allow-circular-references: true
  sql:
    init:
      platform: mysql
      mode: always
      continue-on-error: true
      schema-locations: classpath*:db/schema/mysql.sql




      #feign+hystrix fallback属性设置  https://blog.csdn.net/Mr_rain/article/details/89472167
      #hystrix:
      #  command:
      # default默认全局生效

    #    default:
    # 具体到feignClient#方法
#    PaymentClient#getTimeout(Integer):
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 9000




server:
  port: 80



logging:
  level:
    kira.learn.cloud.app.feign.PaymentClient: debug

#feign.circuitbreaker.enable和 feign.sentinel.enable都生效。
feign:
  client:
    config:
      #key对应feignClient name
      payment:
        #不设置connectTimeout会导致readTimeout设置不生效
        connectTimeout: 3000
        readTimeout: 2000

  #  circuitbreaker:
  #    enabled: true
  sentinel:
    enabled: true
