spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
        - id: order_route
          uri: lb://order
#          uri: http://127.0.0.1
          predicates:
            - Path=/order/**


server:
  port: 9527

