spring:
  application:
    name: user
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
#  security:
#    user:
#      name: admin
#      password: 123456


  datasource:
    url: jdbc:${spring.sql.init.platform}://192.168.1.4:3306/kira_cloud_user?createDatabaseIfNotExist=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Zhangxu00!
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      platform: mysql
      continue-on-error: false
      schema-locations: classpath*:db/schema/init-schema-mysql.sql
      data-locations: classpath*:db/data/init-data-mysql.sql
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret