spring:
  application:
    name: payment
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:${spring.sql.init.platform}://192.168.4.64:3306/kira_cloud?createDatabaseIfNotExist=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root@hiekn
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      platform: mysql
      mode: always
      continue-on-error: true
      schema-locations: classpath*:db/schema/mysql.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:config/public.txt


server:
  port: 8001

#web:
#  security:
#    excludeUrls:
#     - /v2/api-docs
#     - /swagger-resources/**
#     - /doc.html
#     - /webjars/**
