server:
  port: 8080
logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
      hibernate: error

management:
  endpoints:
    web:
      exposure:
        include: 'startup'